### ISSUE TITLE
Shift to a more Redux like approach

### ISSUE THREAD

**Issue by etiennelenhart** [etiennelenhart/Eiffel#50]
While the use of `ViewModel` functions for UI events, simple `updateState()` calls and conventions for `ViewState`s is easy to implement, some problems concerning concurrent state updates and testability may arise.

To accommodate this, Eiffel's approach should be shifted to a more Redux like approach with typed actions and clearly defined state updates.

Related issues:
- [x] #51 Add 'EiffelViewModel' with state reducing and action dispatching
- [x] #52 Add 'Interception' to run side effects on action dispatch
- [x] #53 Add 'Command' interceptions for coroutine side effects
- [x] #58 Add 'observeProperty' function to 'EiffelViewModel'
- [x] #60 Debugging mode

**Comment by etiennelenhart** [comment]
Shift to Redux/MVI approach is basically done.
